server:
  port: 9107
spring:
  application:
    name: cloudalibaba-sentinelmain-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.134:8084 #nacos服务端地址，Nginx做了代理
    sentinel:
      transport:
        dashboard: localhost:8080 #SentinelMain dashboard地址
        port: 8719 #默认端口为8719，如果被占用开始+1扫描，直到找到未被占用的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true
