server:
  port: 8081

spring:
  application:
    name: cloud-consumer-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    fetch-registry: true #是否抓取已有的注册信息，默认为true，单节点无所谓，集群时必须设置为true才能配合Ribbon使用负载均衡
    register-with-eureka: true #是否将自己注册进Eureka Server
    service-url:
      defaultZone: http://eureka1.com:9090/eureka/,http://eureka2.com:9091/eureka/
  instance:
    instance-id: order-server
    prefer-ip-address: true #访问信息可以显示IP地址
    lease-renewal-interval-in-seconds: 1 #客户端向服务端发送心跳的时间间隔默认间隔30秒发送一次(单位:m)
    lease-expiration-duration-in-seconds: 2 #服务端在收到客户端最后一次心跳的等待时间上线(默认90)