server:
  port: 9097
spring:
                application:
                  name: cloud-gateway
                cloud:
                  gateway:
                    discovery:
                      locator:
                        enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
                    routes: #路由设置，可以设置多个路由
                      - id: payment_routh #路由的ID，没有固定规则但要求唯一(建议配合服务名)
                        uri: lb://CLOUD-PAYMENT-SERVER #匹配后提供服务的路由地址
                        predicates: #断言路径相匹配进行断言
                          - Path=/payment/select/**
                      - id: payment_routh2
                        uri: lb://CLOUD-PAYMENT-SERVER
                        predicates:
                          - Path=/payment/time

eureka:
  instance:
    hostname: cloud-gateway-server
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1.com:9090/eureka/,http://eureka2.com:9091/eureka/