server:
  port: 9211
spring:
  application:
    name: seata-stock
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.134:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/seata_repertory?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.gjt.mm.mysql.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml