spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 #已删除字段值为1
      logic-not-delete-value: 0 #正常,字段值为2
  type-enums-package: com.example.springboot_mybatisplus_dome.myenum